import type { EmpireDef, EmpireId } from "./types";
import { CAPITOL, HOUSES } from "./types";
import { TERRITORIES } from "./world";

function homesOn(...continents: string[]): string[] {
  return TERRITORIES.filter((t) => continents.includes(t.continent)).map((t) => t.id);
}

export const EMPIRES: Record<EmpireId, EmpireDef> = {
  asgard: {
    id: "asgard",
    name: "Asgard",
    adjective: "Asgardian",
    capitol: CAPITOL.asgard,
    region: "at",
    homes: homesOn("at"),
    color: "#6fe0ff",
    blurb: "Polar bears on the southern ice.",
    stoneOnAt: true,
    portGoldCost: 3,
    capitalPort: true,
    startShip: true,
  },
  eldorado: {
    id: "eldorado",
    name: "El Dorado",
    adjective: "Doradan",
    capitol: CAPITOL.eldorado,
    region: "sa",
    homes: homesOn("sa"),
    color: "#f0a33c",
    blurb: "Gorillas in the green interior.",
    capitalMine: true,
  },
  aztec: {
    id: "aztec",
    name: "Mayan",
    adjective: "Mayan",
    capitol: CAPITOL.aztec,
    region: "ca",
    homes: homesOn("ca"),
    color: "#ef233c",
    blurb: "Jaguars. Gold from every Central American land.",
    goldOnCa: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  tartaria: {
    id: "tartaria",
    name: "Kunlun",
    adjective: "Kunlun",
    capitol: CAPITOL.tartaria,
    region: "ae",
    homes: homesOn("ae"),
    color: "#3b82f6",
    blurb: "Tigers. Cheap mines in East Asia.",
    stoneOnAs: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  siberia: {
    id: "siberia",
    name: "Siberia",
    adjective: "Siberian",
    capitol: CAPITOL.siberia,
    region: "aw",
    homes: homesOn("aw"),
    color: "#8f6a43",
    blurb: "Grizzlies on the western steppe.",
    stoneOnAs: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  lumuria: {
    id: "lumuria",
    name: "Shangri-La",
    adjective: "Shangri-La",
    capitol: CAPITOL.lumuria,
    region: "ss",
    homes: homesOn("ss"),
    color: "#f43f9a",
    blurb: "Rhinos through the monsoon.",
    woodOnAs: true,
    portGoldCost: 3,
  },
  egypt: {
    id: "egypt",
    name: "Egypt",
    adjective: "Egyptian",
    capitol: CAPITOL.egypt,
    region: "an",
    homes: homesOn("an"),
    color: "#f5c542",
    blurb: "Lions. African grain.",
    foodOnAf: true,
    farmGoldCost: 2,
  },
  sumer: {
    id: "sumer",
    name: "Sumer",
    adjective: "Sumerian",
    capitol: CAPITOL.sumer,
    region: "me",
    homes: homesOn("me"),
    color: "#c9a227",
    blurb: "Giants at the river fork. Middle East gold.",
    capitalMine: true,
    mineGoldCost: 2,
  },
  cape: {
    id: "cape",
    name: "Karoo",
    adjective: "Karoo",
    capitol: CAPITOL.cape,
    region: "af",
    homes: homesOn("af"),
    color: "#22c55e",
    blurb: "Hippos. African timber.",
    woodOnAf: true,
    shipWoodCost: 4,
  },
  gondwana: {
    id: "gondwana",
    name: "Sahul",
    adjective: "Sahulian",
    capitol: CAPITOL.gondwana,
    region: "oc",
    homes: homesOn("oc"),
    color: "#ff8a65",
    blurb: "Crocodiles on the southern shelf.",
    goldOnOc: true,
    portGoldCost: 3,
    capitalMine: true,
    startShip: true,
  },
  thule: {
    id: "thule",
    name: "Nord",
    adjective: "Nordic",
    capitol: CAPITOL.thule,
    region: "ne",
    homes: homesOn("ne"),
    color: "#7eb6d9",
    blurb: "Sabertooths on the eastern ice.",
    stoneOnNa: true,
    castleCost: 6,
  },
  alaska: {
    id: "alaska",
    name: "Alaska",
    adjective: "Alaskan",
    capitol: CAPITOL.alaska,
    region: "nw",
    homes: homesOn("nw"),
    color: "#d7c4a3",
    blurb: "Mammoths at the Bering gate.",
    stoneOnNa: true,
    castleCost: 6,
  },
  atlantis: {
    id: "atlantis",
    name: "Atlantis",
    adjective: "Atlantean",
    capitol: CAPITOL.atlantis,
    region: "eu",
    homes: homesOn("eu"),
    color: "#2ad4cc",
    blurb: "Direwolves on Europe’s stone.",
    stoneOnEu: true,
    castleCost: 4,
  },
};

export const EMPIRE_LIST: EmpireDef[] = HOUSES.map((id) => EMPIRES[id]);

export function empireOf(id: EmpireId): EmpireDef {
  return EMPIRES[id];
}
