import type { EmpireDef, EmpireId } from "./types";
import { CAPITOL } from "./types";

export const EMPIRES: Record<EmpireId, EmpireDef> = {
  atlantis: {
    id: "atlantis",
    name: "Atlantis",
    adjective: "Atlantean",
    capitol: CAPITOL.atlantis,
    homes: ["roma", "iberia", "gaul", "balkans", "rhine"],
    color: "#2ad4cc",
    blurb: "Direwolves. Dragons wake on Europe’s stone.",
    stoneOnEu: true,
    castleCost: 4,
  },
  lumuria: {
    id: "lumuria",
    name: "Shangri-La",
    adjective: "Shangri-La",
    capitol: CAPITOL.lumuria,
    homes: ["india", "himalaya", "indochina", "canton", "malaya", "gulf", "burma", "yunnan"],
    color: "#f43f9a",
    blurb: "Rhinos. Cheap harbours and a path to the islands.",
    woodOnAs: true,
    portGoldCost: 3,
  },
  eldorado: {
    id: "eldorado",
    name: "El Dorado",
    adjective: "Doradan",
    capitol: CAPITOL.eldorado,
    homes: ["amazon", "grenada", "guiana", "brazil", "cerrado", "pantanal"],
    color: "#f0a33c",
    blurb: "A mine already sunk. Black caiman.",
    capitalMine: true,
  },
  aztec: {
    id: "aztec",
    name: "Mayan",
    adjective: "Mayan",
    capitol: CAPITOL.aztec,
    homes: ["mexico", "yucatan", "sierra", "texas", "panama", "oaxaca", "baja"],
    color: "#ef233c",
    blurb: "Jaguars. Gold from every Central American land.",
    goldOnCa: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  asgard: {
    id: "asgard",
    name: "Asgard",
    adjective: "Asgardian",
    capitol: CAPITOL.asgard,
    homes: ["alaska", "yukon", "cascade", "hudson", "hawaii", "aleut", "mackenzie", "columbia", "ontario"],
    color: "#6fe0ff",
    blurb: "Buffalo. Timber and a cheap sail to Hawaii.",
    woodOnNa: true,
    portGoldCost: 3,
  },
  tartaria: {
    id: "tartaria",
    name: "Kunlun",
    adjective: "Kunlun",
    capitol: CAPITOL.tartaria,
    homes: ["cathay", "gobi", "nippon", "siberia", "baikal", "yakutia", "chukotka", "jiangnan", "tarim", "korea"],
    color: "#3b82f6",
    blurb: "Cheap mines. Asian stone for walls and dragons.",
    stoneOnAs: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  egypt: {
    id: "egypt",
    name: "Egypt",
    adjective: "Egyptian",
    capitol: CAPITOL.egypt,
    homes: ["nile", "maghreb", "horn", "nubia", "guinea", "kaabu", "sahel", "kanem", "congo", "teke", "sahara", "gaetulia", "somali", "kasai", "lunda"],
    color: "#f5c542",
    blurb: "Lions. African grain. Pyramids hold the first dragon.",
    foodOnAf: true,
    farmGoldCost: 2,
  },
  babylon: {
    id: "babylon",
    name: "Sumer",
    adjective: "Sumerian",
    capitol: CAPITOL.babylon,
    homes: ["mesopotamia", "arabia", "persia", "anatolia", "armenia", "hejaz"],
    color: "#c084fc",
    blurb: "Two rivers. Elephants. Gold markets. Dragons on the Tigris.",
    goldOnMe: true,
    marketGoldCost: 2,
  },
  cape: {
    id: "cape",
    name: "Karoo",
    adjective: "Karoo",
    capitol: CAPITOL.cape,
    homes: ["cape", "khoi", "madagascar", "sakalava", "rift", "kilwa", "guinea", "congo", "namib", "damara", "nyasa", "yao", "kasai", "lunda"],
    color: "#22c55e",
    blurb: "Hippos. African timber for a dragon fleet.",
    woodOnAf: true,
    shipWoodCost: 4,
  },
  gondwana: {
    id: "gondwana",
    name: "Sahul",
    adjective: "Sahulian",
    capitol: CAPITOL.gondwana,
    homes: ["coral", "outback", "westralia", "aotearoa", "tasmania", "polynesia", "nullarbor", "kimberley"],
    color: "#ff8a65",
    blurb: "Crocodiles. A keel at dawn.",
    goldOnOc: true,
    portGoldCost: 3,
    capitalPort: true,
    startShip: true,
  },
  thule: {
    id: "thule",
    name: "Nord",
    adjective: "Nordic",
    capitol: CAPITOL.thule,
    homes: ["greenland", "westgreenland", "baffin", "labrador", "seaboard", "highlands", "fjords", "acadia", "florida"],
    color: "#7eb6d9",
    blurb: "Ice citadel. Polar bears. A keel and a road into Baffin.",
    stoneOnNa: true,
    castleCost: 6,
    capitalPort: true,
    startShip: true,
  },
};

export const EMPIRE_LIST: EmpireDef[] = Object.values(EMPIRES);

export function empireOf(id: EmpireId): EmpireDef {
  return EMPIRES[id];
}
