import type { EmpireDef, EmpireId } from "./types";
import { CAPITOL } from "./types";
import { TERRITORIES } from "./world";

function homesOn(...continents: string[]): string[] {
  return TERRITORIES.filter((t) => continents.includes(t.continent)).map((t) => t.id);
}

export const EMPIRES: Record<EmpireId, EmpireDef> = {
  atlantis: {
    id: "atlantis",
    name: "Atlantis",
    adjective: "Atlantean",
    capitol: CAPITOL.atlantis,
    homes: homesOn("eu"),
    color: "#2ad4cc",
    blurb: "Direwolves. Dragons wake on Europe’s stone.",
    stoneOnEu: true,
    castleCost: 4,
  },
  lumuria: {
    id: "lumuria",
    name: "Shangri-La",
    adjective: "Shangri-La",
    capitol: CAPITOL.lumuria,
    homes: homesOn("ss"),
    color: "#f43f9a",
    blurb: "Rhinos. Cheap harbours and a path through Sundaland.",
    woodOnAs: true,
    portGoldCost: 3,
  },
  eldorado: {
    id: "eldorado",
    name: "El Dorado",
    adjective: "Doradan",
    capitol: CAPITOL.eldorado,
    homes: homesOn("sa"),
    color: "#f0a33c",
    blurb: "A mine already sunk in the interior. Black caiman.",
    capitalMine: true,
  },
  aztec: {
    id: "aztec",
    name: "Mayan",
    adjective: "Mayan",
    capitol: CAPITOL.aztec,
    homes: homesOn("ca"),
    color: "#ef233c",
    blurb: "Jaguars. Gold from every Central American land, and Hawaiki.",
    goldOnCa: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  asgard: {
    id: "asgard",
    name: "Asgard",
    adjective: "Asgardian",
    capitol: CAPITOL.asgard,
    homes: homesOn("at"),
    color: "#6fe0ff",
    blurb: "Penguins on the southern ice. A keel at the shelf.",
    stoneOnAt: true,
    portGoldCost: 3,
    capitalPort: true,
    startShip: true,
  },
  tartaria: {
    id: "tartaria",
    name: "Kunlun",
    adjective: "Kunlun",
    capitol: CAPITOL.tartaria,
    homes: homesOn("aw", "ae"),
    color: "#3b82f6",
    blurb: "Cheap mines. Asian stone for walls and dragons.",
    stoneOnAs: true,
    mineGoldCost: 2,
    mineStoneCost: 2,
  },
  egypt: {
    id: "egypt",
    name: "Egypt",
    adjective: "Egyptian",
    capitol: CAPITOL.egypt,
    homes: homesOn("an"),
    color: "#f5c542",
    blurb: "Lions. African grain. Pyramids hold the first dragon.",
    foodOnAf: true,
    farmGoldCost: 2,
  },
  babylon: {
    id: "babylon",
    name: "Sumer",
    adjective: "Sumerian",
    capitol: CAPITOL.babylon,
    homes: homesOn("me"),
    color: "#c084fc",
    blurb: "Two rivers. Elephants. Gold markets. Dragons on the Tigris.",
    goldOnMe: true,
    marketGoldCost: 2,
  },
  cape: {
    id: "cape",
    name: "Karoo",
    adjective: "Karoo",
    capitol: CAPITOL.cape,
    homes: homesOn("af"),
    color: "#22c55e",
    blurb: "Hippos. African timber for a dragon fleet.",
    woodOnAf: true,
    shipWoodCost: 4,
  },
  gondwana: {
    id: "gondwana",
    name: "Sahul",
    adjective: "Sahulian",
    capitol: CAPITOL.gondwana,
    homes: homesOn("oc"),
    color: "#ff8a65",
    blurb: "Crocodiles. A keel at dawn on the southern shelf.",
    goldOnOc: true,
    portGoldCost: 3,
    capitalMine: true,
    startShip: true,
  },
  thule: {
    id: "thule",
    name: "Nord",
    adjective: "Nordic",
    capitol: CAPITOL.thule,
    homes: homesOn("nw", "ne"),
    color: "#7eb6d9",
    blurb: "Buffalo on the Laurentide fringe. Stone from every American land.",
    stoneOnNa: true,
    castleCost: 6,
  },
};

export const EMPIRE_LIST: EmpireDef[] = Object.values(EMPIRES);

export function empireOf(id: EmpireId): EmpireDef {
  return EMPIRES[id];
}
